spring:
  datasource:
    url: jdbc:sqlserver://pawvsql01.database.windows.net:1433;databaseName=ASSET_TRACKING;sendStringParametersAsUnicode=false
    username: weblogin
    password: k!W3b109!n
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


